name: Release GEO

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          #sing-box
          sb=1.9.6
          curl -L https://github.com/SagerNet/sing-box/releases/download/v$sb/sing-box-$sb-linux-amd64.tar.gz  -o sing-box-$sb-linux-amd64.tar.gz
          tar xzvf sing-box-$sb-linux-amd64.tar.gz
          mv ./sing-box-$sb-linux-arm64/sing-box /root
          chmod +x ./sing-box
          rm -r ./sing-box-$sb-linux-arm64.tar.gz
          rm -r ./sing-box-$sb-linux-arm64

      - name: Generate Geo Rule
        run: |
          chmod +x script/generate.sh
          bash script/generate.sh

      - name: Set timezone to WIB Jakarta
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Indonesia Standard Time"

      - name: Set Date
        id: set_date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        run: |
          TAG="geo-rule-${{ env.DATE }}"
          echo "Creating release: $TAG"
          upload_url=$(gh release create "$TAG" --title "Release $TAG" --notes "Automated release for $TAG" --json uploadUrl -q .uploadUrl)
          echo "upload_url=$upload_url" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ./conf/rules/*.srs  # Jalur ke semua file .srs
          asset_name: ${{ github.run_id }}-output.srs  # Misalnya, gunakan ID run untuk penamaan
          asset_content_type: application/octet-stream


      - name: Delete Old Release
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          repo: faidc/geo-rule
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
