name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          #sing-box
          sb=1.9.6
          curl -L https://github.com/SagerNet/sing-box/releases/download/v$sb/sing-box-$sb-linux-amd64.tar.gz  -o sing-box-$sb-linux-amd64.tar.gz
          tar xzvf sing-box-$sb-linux-amd64.tar.gz
          sudo mv ./sing-box-$sb-linux-amd64/sing-box /usr/local/bin/sing-box
          rm -r ./sing-box-$sb-linux-amd64.tar.gz
          rm -r ./sing-box-$sb-linux-amd64
          chmod +x /usr/local/bin/sing-box
          
      - name: Generate Geo Rule
        run: |
          chmod +x script/generate.sh
          sudo bash script/generate.sh

      - name: Set timezone to WIB Jakarta
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Indonesia Standard Time"

      - name: Set Date
        id: set_date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v1.0.0" --title "Release Title" --notes "Release Notes" --draft
  
      - name: List Files in Workspace
        run: |
          ls -l $GITHUB_WORKSPACE/

      - name: Upload All Rule Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Menggunakan GitHub token default
        run: |
          for file in $GITHUB_WORKSPACE/*.srs; do
            echo "Uploading $file"
            gh release upload ${{ steps.create_release.outputs.upload_url }} "$file" --clobber
            echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"
          done

      - name: Delete Old Release
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          repo: faidc/geo-rule
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
